# Generated by Django 5.2.9 on 2026-03-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("client_id", models.AutoField(primary_key=True, serialize=False)),
                ("client_name", models.CharField(max_length=100)),
                ("client_adresse", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=100)),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
