# Generated by Django 5.2.9 on 2026-03-02 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fidpha", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("contract_id", models.AutoField(primary_key=True, serialize=False)),
                ("contract_number", models.CharField(max_length=50, unique=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="fidpha.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("factor", models.FloatField()),
                ("amount_threshold", models.PositiveIntegerField()),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fidpha.contract",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fidpha.product"
                    ),
                ),
            ],
            options={
                "unique_together": {("contract", "product")},
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="products",
            field=models.ManyToManyField(
                through="fidpha.ContractProduct", to="fidpha.product"
            ),
        ),
    ]
