# Generated by Django 5.2.9 on 2026-03-04 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fidpha", "0003_client_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sells",
            fields=[
                ("sell_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("sell_date", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fidpha.client"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fidpha.contract",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fidpha.product"
                    ),
                ),
            ],
            options={
                "db_table": "Sells",
                "managed": True,
            },
        ),
    ]
